/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.bankAccounts.BaseBankAccount;
import org.example.factories.BankAccountFactory;
import org.example.factories.BankAccountOwnerFactory;
import org.example.people.BankAccountOwner;
import org.example.services.BankAccountService;

public class App {
	public static void main(String[] args) {
		BankAccountFactory bankAccountFactory = new BankAccountFactory();
		BankAccountService bankAccountService = new BankAccountService();
		BankAccountOwnerFactory bankAccountOwnerFactory = new BankAccountOwnerFactory();

		BankAccountOwner owner = bankAccountOwnerFactory.createBankAccountOwner("Jarda", "Nohavica");
		BaseBankAccount account = bankAccountFactory.createSavingBankAccount("u-123", owner);

		bankAccountService.deposit(account, 500);

		System.out.println(account.getBalance());
	}
}
